config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get ALL
  get 'tasks', to: 'tasks#index'

  # update a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'

  # Create one task(needs two steps)
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # get ONE
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  # destroy a task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  protect_from_forgery
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    if @task.save
      redirect_to task_path(@task)
    else
      redirect_to task_new_path
    end
  end

  def edit
    @task = Task.find(params[:id])
    # render a form with the existing object
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
    # make changes presistant
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |t| %>
  <%= t.label :title, 'Title' %>
  <%= t.text_field :title %>
  <%= t.label :details, 'Details' %>
  <%= t.text_field :details %>
  <%= t.label :completed, 'Completed?' %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
  <li>
    <%= check_box("tag", task.completed, {checked: task.completed}) %>
    <%= link_to "#{task.title}", task_path(task) %>
  </li>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>


<!-- <form method="post" action="/tasks">

  <label for="title">Title</label>
  <input type="text" name="task[title]">

  <label for="details">Details</label>
  <input type="text" name="task[details]">

  <input type="submit" >
</form>
 -->

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<h2><%= @task.details %></h2>

<%if @task.completed %>
  <%= check_box("tag", @task.completed, {checked: @task.completed})%>
  <%= "Task is completed!" %>
<% else %>
  <%=check_box("tag", @task.completed, {checked: @task.completed})%>
  <%= "This task is not yet completed!" %>
<% end %>

<p><%= link_to 'Go back to main list', tasks_path %></p>
<h1><%= link_to 'Edit this task', edit_task_path %></h1>